### PR TITLE
fixing RefSystemTest

### LINKED ISSUE #560: Fix RefSystemTest
`testTolerance < Math.abs(actual.getValue().doubleValue() - expected.getValue().doubleValue())` should be changed to (actual - expected) < testTolerance

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #560

### CODE REVIEW

File: src/test/groovy/edu/ie3/simona/model/grid/RefSystemTest.groovy [hunk 1]
```diff
@@ -47,28 +47,28 @@ class RefSystemTest extends Specification {
...
     when:
     Quantity<Dimensionless> actual = RefSystem.transferImpedance(impedance, from, to)
 
     then:
     actual.getUnit() == impedance.getUnit()
-    testTolerance < Math.abs(actual.getValue().doubleValue() - expected.getValue().doubleValue())
+    Math.abs(actual.getValue().doubleValue() - expected.getValue().doubleValue()) < testTolerance
   }
 
   def "An dimensionless admittance is transferred correctly between to reference system"() {
```
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/simona/model/grid/RefSystemTest.groovy:60]: "between to" looks like a slip-up... Could be "between reference systems". Would you correct this, also in the test title above?

**Review by sebastian-peter — DISMISSED** [review]
Unreal that we had these broken tests in here without noticing... Thanks for fixing this!

I have only a small wish for another small fix in there.

**Review by julianhohmann — APPROVED** [review]
