### PR TITLE
Fix unreliable ThermalGridIT/EmAgentIT

### LINKED ISSUE #1757: Fix unreliable `ThermalGridIT`/`EmAgentIT`
Sometimes, `ThermalGridIT` fails because of a race condition within the test.

edu.ie3.simona.agent.grid.ThermalGridIT > A Thermal Grid with thermal house, thermal storage and heat pump that is controlled by an energy management should be initialized correctly and run through some activations FAILED
    org.scalatest.exceptions.TestFailedException: Vector(ExpectResult(1b5e928e-65a3-444c-b7f2-6a48af092224, 46800, true), ExpectResult(9dc7123f-b0e0-4ec3-ba46-acbc35eb1c5d, 46800, true), ExpectResult(1b5e928e-65a3-444c-b7f2-6a48af092224, 46800, false), ParticipantResultEvent(HpResult{time=2020-06-01T23:00Z, inputModel=1b5e928e-65a3-444c-b7f2-6a48af092224, p=0.0038 MW, q=0.0012489995996796802 Mvar, qDot=0.011 MW})) did not contain all of (ExpectResult(1b5e928e-65a3-444c-b7f2-6a48af092224, 46800, true), ExpectResult(9dc7123f-b0e0-4ec3-ba46-acbc35eb1c5d, 46800, true), ExpectResult(1b5e928e-65a3-444c-b7f2-6a48af092224, 46800, false), ExpectResult(9dc7123f-b0e0-4ec3-ba46-acbc35eb1c5d, 46800, false))
        at app//org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
        at app//org.scalatest.matchers.dsl.ResultOfContainWord.allOf(ResultOfContainWord.scala:298)
        at app//edu.ie3.simona.agent.grid.ThermalGridIT.f$proxy2$1(ThermalGridIT.scala:3544)
        at app//edu.ie3.simona.agent.grid.ThermalGridIT.$init$$$anonfun$2$$anonfun$1(ThermalGridIT.scala:1346)

Can probably be fixed if the two message probes are combined into one (**there's also more vulnerable instances in this test class**, this is just an example).
https://github.com/ie3-institute/simona/blob/f92c17a7b3e09351e262633bb13536f5ac0c623a/src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala#L3537-L3578

`EmAgentIT` seems to have a similar problem sometimes:

edu.ie3.simona.agent.em.EmAgentIT > An em agent when having load, pv and storage agents connected should be initialized correctly and run through some activations FAILED
    java.lang.AssertionError: expected ExpectResult(46fb0164-5522-4732-b7bb-678d3e5cc09b,7200,true), found NoResult(f976a305-5fa7-4a9d-b599-8616b59fc658,7200)
        at org.apache.pekko.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:410)
        at org.apache.pekko.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:181)
        at org.apache.pekko.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:160)
        at edu.ie3.simona.agent.em.EmAgentIT.f$proxy1$1(EmAgentIT.scala:288)
        at edu.ie3.simona.agent.em.EmAgentIT.f$proxy4$1$$anonfun$1$$anonfun$1(EmAgentIT.scala:95)

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1757 

This changes:
- variable naming of `HpInput` and `HpTypeInput` used for `EmAgentIT`
- removes some unused inputs in `HpInputTestData`
- combines two separate result event messages evaluation in `EmAgentIT`
- restructures the evaluation of result event messages within ThermalGridIT

### CODE REVIEW

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala [hunk 1]
```diff
@@ -234,55 +234,45 @@ class ThermalGridIT
...
+          case (uuid, time, qDot, energy)
+              if uuid == typicalHeatStorage.getUuid =>
+            time shouldBe 0.toDateTime
+            qDot should equalWithTolerance(0.011.asMegaWatt)
+            energy should equalWithTolerance(0.asMegaWattHour)
+          case (uuid, time, qDot, energy)
+              if uuid == littleDomesticHotWaterStorageInput.getUuid =>
+            time shouldBe 0.toDateTime
+            qDot should equalWithTolerance(-0.005405957260274.asMegaWatt)
+            energy should equalWithTolerance(0.000522.asMegaWattHour)
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala]: The way this was structured before (with `case ThermalResultEvent(thermalUnitResult) =>`) looked a bit more concise, but guess that's up to personal preference. Or, maybe matching against this like below, and combining the two collect operations? 

```scala
        case ThermalResultEvent(
              AbstractThermalStorageResult(time, inputModel, qDot, energy)
            ) if uuid == typicalHeatStorage.getUuid =>
        [...]
```

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala [hunk 2]
```diff
@@ -1549,56 +1302,44 @@ class ThermalGridIT
...
+          qDot should equalWithTolerance(0.asMegaWatt)
+          indoorTemp should equalWithTolerance(20.asDegreeCelsius)
+      }
+
+      msg0
+        .collect {
+          case ThermalResultEvent(
+                AbstractThermalStorageResult(time, inputModel, qDot, energy)
+              ) =>
+            (inputModel, time, qDot, energy)
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala]: Same as above

File: src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala:1]: There's more consecutive `resultServiceProxy.receiveMessages` in here that could also be unreliable, but I guess the most annoying one here is fixed now :)

**Review by sebastian-peter — COMMENTED** [review]
Thanks for the additional cleanup!

**Review by sebastian-peter — APPROVED** [review]
