### PR TITLE
Removed message retrieval timeout from DBFS

### LINKED ISSUE #1422: Remove message retrieval timeout from powerflow calculation
Message timeouts (`ask`) have been increased from 3s to 30s, but on (memory-)limited machines this might still not be enough.
My suggestion would be to remove the timeout alltogether (which might mean we have to move away from the ask pattern). We very rarely rely on the ask pattern anyways and normally just react to received messages.

```
14:27:46.517 INFO  o.a.pekko.pattern.PromiseActorRef - Message [edu.ie3.simona.agent.grid.GridAgentMessages$GridPowerResponse] to Actor[pekko://Simona/temp/2$e] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[pekko://Simona/temp/2$e] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'pekko.log-dead-letters' and 'pekko.log-dead-letters-during-shutdown'.
14:27:46.558 ERROR o.a.pekko.actor.SupervisorStrategy - (WrappedFailure(java.util.concurrent.TimeoutException: Ask timed out on [Actor[pekko://Simona/user/2#1142587307]] after [30000 ms]. Message of type [edu.ie3.simona.agent.grid.GridAgentMessages$RequestGridPower]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.),GridAgentBaseData(GridEnvironment(GridModel(1,RefSystem(20.0 kV,1732.0508075688774 A,60.0 MW,6.666666666666667 Ω),GridComponents(List(NodeModel(4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5,MV1.101 Bus 52,Interval [0, 2678400],true,0.9650000000000001 ea,CommonVoltageLevel{id='Mittelspannung', nominalVoltage=20.0 kV, synonymousIds=[Mittelspannung, ms, ms_20kv, mv, mv_20kV], voltageRange=Interval [20.0 kV, 30.0 kV)})),Set(),Set(),Set(),Set()),GridControls(Set(TransformerControlGroupModel(Set(),edu.ie3.simona.model.control.TransformerControlGroupModel$$$Lambda$1102/0x00007f36b0580780@27319ab3), TransformerControlGroupModel(Set(),edu.ie3.simona.model.control.TransformerControlGroupModel$$$Lambda$1102/0x00007f36b0580780@7eb40133)))),Map(SubGridTopolgyEdge{link=Transformer2WInput(7dcc88ae-e2ec-4c28-90be-44b8f7a5fe39), superiorNode=4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5 subgrid 1, inferiorNode=5ff3164e-b127-4cc1-b847-50277d505d7f subgrid 2} -> Actor[pekko://Simona/user/2#1142587307]),Map()),PowerFlowParams(1.0E-5,Vector(1.0E-12),50,PT30S,true),0,ReceivedValuesStore(Map(4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5 -> Map(Actor[pekko://Simona/user/2#1142587307] -> None)),Map()),Map(),1)) (of class scala.Tuple2)
scala.MatchError: (WrappedFailure(java.util.concurrent.TimeoutException: Ask timed out on [Actor[pekko://Simona/user/2#1142587307]] after [30000 ms]. Message of type [edu.ie3.simona.agent.grid.GridAgentMessages$RequestGridPower]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.),GridAgentBaseData(GridEnvironment(GridModel(1,RefSystem(20.0 kV,1732.0508075688774 A,60.0 MW,6.666666666666667 Ω),GridComponents(List(NodeModel(4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5,MV1.101 Bus 52,Interval [0, 2678400],true,0.9650000000000001 ea,CommonVoltageLevel{id='Mittelspannung', nominalVoltage=20.0 kV, synonymousIds=[Mittelspannung, ms, ms_20kv, mv, mv_20kV], voltageRange=Interval [20.0 kV, 30.0 kV)})),Set(),Set(),Set(),Set()),GridControls(Set(TransformerControlGroupModel(Set(),edu.ie3.simona.model.control.TransformerControlGroupModel$$$Lambda$1102/0x00007f36b0580780@27319ab3), TransformerControlGroupModel(Set(),edu.ie3.simona.model.control.TransformerControlGroupModel$$$Lambda$1102/0x00007f36b0580780@7eb40133)))),Map(SubGridTopolgyEdge{link=Transformer2WInput(7dcc88ae-e2ec-4c28-90be-44b8f7a5fe39), superiorNode=4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5 subgrid 1, inferiorNode=5ff3164e-b127-4cc1-b847-50277d505d7f subgrid 2} -> Actor[pekko://Simona/user/2#1142587307]),Map()),PowerFlowParams(1.0E-5,Vector(1.0E-12),50,PT30S,true),0,ReceivedValuesStore(Map(4354195b-c2f5-4b0f-a1a0-02bd4a52e0d5 -> Map(Actor[pekko://Simona/user/2#1142587307] -> None)),Map()),Map(),1)) (of class scala.Tuple2)
	at edu.ie3.simona.agent.grid.DBFSAlgorithm$$anonfun$simulateGrid$1.applyOrElse(DBFSAlgorithm.scala:79)
	at edu.ie3.simona.agent.grid.DBFSAlgorithm$$anonfun$simulateGrid$1.applyOrElse(DBFSAlgorithm.scala:77)
	at org.apache.pekko.actor.typed.scaladsl.Behaviors$.$anonfun$receivePartial$1(Behaviors.scala:162)
	at org.apache.pekko.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:147)
	at org.apache.pekko.actor.typed.Behavior$.interpret(Behavior.scala:311)
	at org.apache.pekko.actor.typed.Behavior$.interpretMessage(Behavior.scala:265)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:141)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.$anonfun$aroundReceive$2(ActorAdapter.scala:109)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:105)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:272)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:233)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:245)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
14:27:46.571 ERROR o.a.pekko.actor.SupervisorStrategy - An actor (Actor[pekko://Simona/user/1#-339641831]) unexpectedly terminated. Stopping all children and reporting simulation failure. See logs and possibly stacktrace for details.
14:27:46.572 ERROR e.i.s.e.l.RuntimeEventListener$ - Simulation stopped with error.
14:27:51.624 INFO  e.i.simona.main.RunSimonaStandalone$ - "Und wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein" - F. Nietzsche
14:27:51.626 INFO  e.i.simona.main.RunSimonaStandalone$ - Goodbye!
14:27:51.625 INFO  o.a.pekko.actor.CoordinatedShutdown - Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
14:27:52.633 ERROR e.i.simona.main.RunSimonaStandalone$ - Simulation stopped due to the occurrence of an error! The full log can be found here: file:///shared/output/sg_lab/vn_simona_2025-06-11_14-25-20/log/simona.log
```

Related issues: #270, #589

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1422

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala:1]: Unnecessary imports

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessages.scala
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessages.scala:1]: `ReceivedSlackVoltageValues` is not sent anymore, thus a bunch of code can be thrown out (also in `DBFSAlgorithm`, `GridAgentData`, ...)

Also unused (then):
- `ReceivedValues`
- `SlackVoltageRequestResponse`
- `WrappedFailure`


Could you also do me a favor and make sure that every scaladoc text includes a reference to corresponding Request or Response?

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala:1]: Lots of unused imports

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala [hunk 1]
```diff
@@ -358,58 +380,51 @@ object GridAgentData {
...
-      val updatedNodeToReceivedPowersMap = receivedPowerValues.values.foldLeft(
-        receivedValueStore.nodeToReceivedPower
-      ) {
-        case (
-              nodeToReceivedPowerValuesMapWithAddedPowerResponse,
-              (
-                senderRef,
+    )(using log: Logger): GridAgentBaseData = {
+      val updatedNodeToReceivedPowersMap =
+        (receivedValueStore.nodeToReceivedPower, receivedPowerValue) match {
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala]: I know this is code you produced, but matching against `receivedValueStore.nodeToReceivedPower` does not make any sense here...

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala [hunk 2]
```diff
@@ -358,58 +380,51 @@ object GridAgentData {
...
+      *   Indicates if already received values should be replaced.
       * @return
-      *   an updated version of this [[GridAgentBaseData]] containing the
-      *   receivedPowerValues
+      *   An updated version of this [[GridAgentBaseData]] containing the
+      *   receivedPowerValues.
       */
-    def updateWithReceivedPowerValues(
-        receivedPowerValues: ReceivedPowerValues,
+    def updateWithPowerResponse(
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:398]: Seems like this is a bit duplicate to what happens in `DBFSAlgorithm.waitForAssetAnswers`

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala [hunk 3]
```diff
@@ -419,74 +434,77 @@ object GridAgentData {
...
+            // add or update entry in map of node entries
+            (senderRef -> Some(powerResponse))
+
+          /* Actually update the map and hand it back */
+          nodeToReceived.updated(uuid, nodeReceived)
+
+        case str: String =>
+          log.warn(str)
+
+          nodeToReceived
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala]: This looks like bad practice tbh... I'd rather have the string logged right away and return an optional UUID above

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
A first review round from my side

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala (hunk 2 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:398]: It is not a duplicate but its similar.

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:1]: More unnecessary imports here

File: src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala:1]: Also here

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala:1]: And still here

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala (hunk 2 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:398]: The issue with `DBFSAlgorithm.waitForAssetAnswers` seems to me that we have a `awaitingData` map that stores received power before then moving them to `data.updateWithPowerResponse` once all have been received. The only reason we do this seems to be that we keep track of whether power values have changed or not: 

https://github.com/ie3-institute/simona/blob/20e80f1709af428bf67d91cd99e43bf59e887d90/src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala#L1159-L1162

This could be a simply boolean value as a parameter of `waitForAssetAnswers`. For this to work we would've needed to clean out the participant powers from `NodeToReceivedPower` (but leave in power values from inferior GridAgents).

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Found a way to trim down `waitForAssetAnswers`, let me know what you think. Considering how big of a mess DBFS is, there would be even more to do, but it's your call if you want to tackle that.

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala (hunk 2 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:398]: This is just an idea from my side though... It'd be another step in simplifying GridAgent and its surroundings

Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala:398]: I will take care of this in #1665.

File: src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala [hunk 4]
```diff
@@ -540,20 +540,25 @@ trait DBFSAlgorithm extends PowerFlowSupport with GridResultsSupport {
                 )
               )
 
+              val nodeToAssetAgents =
+                gridAgentBaseData.gridEnv.nodeToAssetAgents
+
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala]: Unnecessary? Only used once

File: src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala [hunk 5]
```diff
@@ -1222,51 +1201,32 @@ trait DBFSAlgorithm extends PowerFlowSupport with GridResultsSupport {
...
+          currentSweepNo,
+          superiorNodes,
+          ctx.self,
         )
-        .map(res => ReceivedSlackVoltageValues(res))
-      pipeToSelf(future, ctx)
+      }
+
       true
     } else false
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala]: Return value is never used...

```suggestion
    superiorGridRefs.foreach { case (superiorGridAgent, superiorNodes) =>
      superiorGridAgent ! SlackVoltageRequest(
        currentSweepNo,
        superiorNodes,
        ctx.self,
      )
    }
```

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala [hunk 6]
```diff
@@ -345,62 +333,28 @@ object GridAgent extends DBFSAlgorithm with DCMAlgorithm {
...
-  private[grid] def pipeToSelf(
-      future: Future[GridAgent.Message],
-      ctx: ActorContext[GridAgent.Message],
-  ): Unit = {
-    ctx.pipeToSelf[GridAgent.Message](future) {
-      case Success(value)     => value
-      case Failure(exception) => WrappedFailure(exception)
-    }
+      true
+    } else false
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala]: Same here

File: src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala [hunk 7]
```diff
@@ -7,17 +7,13 @@
...
 import edu.ie3.simona.agent.grid.GridAgentMessages.Responses.ExchangeVoltage
-import edu.ie3.simona.agent.grid.ReceivedValuesStore.{
-  NodeToReceivedPower,
-  NodeToReceivedSlackVoltage,
-}
+import edu.ie3.simona.agent.grid.ReceivedValuesStore.*
 import edu.ie3.simona.agent.participant.ParticipantAgent
+import edu.ie3.simona.util.CollectionUtils.emptyOptionMap
 import org.apache.pekko.actor.typed.ActorRef
+import org.slf4j.Logger
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala]: Unused import

File: src/main/scala/edu/ie3/simona/util/CollectionUtils.scala [hunk 8]
```diff
@@ -26,6 +26,15 @@ object CollectionUtils {
...
   }
 
+  def emptyOptionMap[K1, K2, V](
+      keys: Map[K1, Iterable[K2]]
+  ): Map[K1, Map[K2, Option[V]]] = keys.map { case (key, infKeys) =>
+    key -> emptyOptionMap(infKeys.toSet)
+  }
+
+  def emptyOptionMap[K, V](keys: Set[K]): Map[K, Option[V]] =
+    keys.map(key => key -> None).toMap
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/util/CollectionUtils.scala:59]: ScalaDoc would be nice :)

**Review by sebastian-peter — DISMISSED** [review]
Looks very good! Only some last comments, I promise

**Review by sebastian-peter — APPROVED** [review]
Thanks!
