### PR TITLE
Fix name and protocol changes within simonaAPI

### LINKED ISSUE #384: Fix breaking SIMONA due to renamed messages and changed protocol in simonaAPI
Since changing names and separating departures and arrivals in message protocol with [simonaAPI#64 ](https://github.com/ie3-institute/simonaAPI/pull/64) and [simonaAPI#78](https://github.com/ie3-institute/simonaAPI/pull/78) SIMONA breaks. This need to be fixed.

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #384 

Mainly based on previous work of @sebastian-peter

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 1]
```diff
@@ -357,42 +353,188 @@ protected trait EvcsAgentFundamentals
...
+      tick,
+      result,
       updatedRelevantData
     )
   }
 
+  /** Handles a evcs movements message that contains information on arriving and
+    * departing vehicles. After applying the movements to the last known set of
+    * parked evs, calculates resulting charging power. Sends completion message
+    * to scheduler without scheduling new activations.
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:392]: The docs need to be updated

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 2]
```diff
@@ -357,42 +353,188 @@ protected trait EvcsAgentFundamentals
...
+        EvcsRelevantData,
+        EvcsModel
+      ],
+      arrivingEvs: Seq[EvModel]
+  ): FSM.State[AgentState, ParticipantStateData[ApparentPower]] = {
+
+    val evcsModel = getEvcsModel(modelBaseStateData)
+
+    val (tickInterval, lastEvs) =
+      getTickIntervalAndLastEvs(tick, modelBaseStateData)
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:419]: s.o. (`currentEvs`)

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 3]
```diff
@@ -357,42 +353,188 @@ protected trait EvcsAgentFundamentals
...
+    /* Update the value stores */
+    val updatedValueStore =
+      ValueStore.updateValueStore(
+        baseStateData.resultValueStore,
+        tick,
+        result
+      )
+    val updatedRelevantDataStore =
+      ValueStore.updateValueStore(
+        baseStateData.calcRelevantDateStore,
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:519]: the `calcRelevantDateStore` should be a "data" and not a "date" store

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 4]
```diff
@@ -517,4 +593,59 @@ protected trait EvcsAgentFundamentals
...
+  /** Checks whether requested departing EVs are consistent with currently
+    * connected EVs. Only logs warnings, does not throw exceptions.
+    *
+    * @param lastEvs
+    *   EVs of the last tick
+    * @param departures
+    *   Departing EVs at the current tick
+    */
+  protected def validateDepartures(
+      lastEvs: Set[EvModel],
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:606]: `currentEvs` ? 🙃

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 5]
```diff
@@ -517,4 +593,59 @@ protected trait EvcsAgentFundamentals
...
+    *
+    * @param lastEvs
+    *   EVs of the last tick
+    * @param arrivals
+    *   Arriving EVs at the current tick
+    * @param chargingPoints
+    *   max number of charging points available at this CS
+    */
+  protected def validateArrivals(
+      lastEvs: Set[EvModel],
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:629]: s.o.

File: src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala [hunk 6]
```diff
@@ -222,70 +220,91 @@ class ExtEvDataService(override val scheduler: ActorRef)
...
+      }
+    }
+
+    val departingEvResponses: Map[UUID, Option[Seq[EvModel]]] =
+      serviceStateData.uuidToActorRef.map { case (evcs, _) =>
+        evcs -> None
+      }
+
+    // if there are no departing evs during this tick,
+    // we're sending response right away
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala:248]: Question: `departingEvResponses.isEmpty` in this simulation would only be true if the `uuidToActorRef` map would be empty. Wouldn't this mean there is no evcs in the simulation instead of there are no departing evs during this tick? 

Did you mean to check `if(allDepartingEvs.isEmpty)` ?

**Review by t-ober — CHANGES_REQUESTED** [review]
Looks very nice ! Just a few minor things 🙂

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 7]
```diff
@@ -307,48 +307,44 @@ protected trait EvcsAgentFundamentals
...
+
     val evServiceRef = getService[ActorEvMovementsService](
       modelBaseStateData.services
     )
 
     val (tickInterval, lastEvs) =
-      getTickIntervalAndLastEvs(currentTick, modelBaseStateData)
+      getTickIntervalAndLastEvs(tick, modelBaseStateData)
+
+    validateDepartures(lastEvs, requestedDepartingEvs)
```
[the remark this answers is not in the document]
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:342]: I wouldn't agree to that since the EVs retrieved here stem from a tick in the past, thus `lastEvs`. This is in contrast to the EVs that are determined for the current tick, namely the ones staying plus arrivals, thus `currentEvs`.

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala [hunk 8]
```diff
@@ -357,42 +353,188 @@ protected trait EvcsAgentFundamentals
...
-        evcsMovementsData.movements
-      )
-      if (departedEvs.nonEmpty) {
-        evServiceRef ! DepartedEvsResponse(
-          evcsModel.uuid,
-          departedEvs
-        )
+    val (departingEvs, stayingEvs) =
+      evModelsCalculated.partition { ev =>
+        // EV has been parked up until now and has now departed
```
[the remark this answers is not in the document]
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:365]: One could argue about semantics here since MobSim determined the departing EVs and that could justify the use of past tense here. But in the end I agree your suggestion seems sensible within the temporal framework that we use here.

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala (hunk 2 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:419]: I didn't rename the variables, but left some clarifying commentary

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala (hunk 3 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:519]: I agree, but 1. I wouldn't change it in this PR and 2. the `calcRelevantDateStore` will be gone with the introduction of flex and stateful agents

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala (hunk 7 above)
[the remark this answers is not in the document]
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:342]: This also makes sense if you look at the naming of `currentTick`, which is the tick currently activated. A tick at which the agent was active _before the current tick_ I would name `lastTick` :)

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala (hunk 4 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:606]: see my explanation above

File: src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala (hunk 6 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala:248]: You're right, this is not right

File: src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala (hunk 7 above)
[the remark this answers is not in the document]
Comment (t-ober) [reply src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala:343]: I see the point (and was expecting that you will make it 😄 ) but I would understand it a bit differently.
Since we haven't dealt with arrivals and departures yet, the current evs are still the evs from last tick. Nevertheless I don't think we have to drag that on here.

**Review by t-ober — APPROVED** [review]
