### PR TITLE
Fixes in Documentation, ScalaDocs, Code Style 

### LINKED ISSUE #1397: Documentation, ScalaDoc and Code Style fixes
Mostly format and other stuff, but from content side there will be changes of
- pattern matching conditions for writting results of ThermalGrid
- additional checks that resultListener expect no more messages in ThermalGridIT and EmAgentIT

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1397

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala [hunk 1]
```diff
@@ -165,21 +165,19 @@ object CylindricalThermalStorage {
...
+      ),
+      KilowattHoursPerKelvinCubicMeters(
+        input.getC
+          .to(PowerSystemUnits.KILOWATTHOUR_PER_KELVIN_TIMES_CUBICMETRE)
+          .getValue
+          .doubleValue
+      ),
+      Celsius(input.getInletTemp.to(Units.CELSIUS).getValue.doubleValue),
+      Celsius(input.getReturnTemp.to(Units.CELSIUS).getValue.doubleValue),
+    )
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala]: Maybe this could be moved to the quantity to squants conversion utils.

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala [hunk 2]
```diff
@@ -321,15 +318,14 @@ final case class ThermalGrid(
   }
 
   /** Handles the case, when the storage has heat demand and will be filled up
-    * here (positive qDot) or will return its stored energy into the thermal
-    * grid (negative qDot).
+    * here (positive qDot).
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala:321]: Is a negative qDot still possible here? Since below you state, that `qDotStorage` can be negative.

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala [hunk 3]
```diff
@@ -517,12 +511,12 @@ final case class ThermalGrid(
...
         lastOpThermals.forall(_.qDotHouse != currentOpThermals.qDotHouse),
-        state.tick != 0,
+        state.tick == 0,
       ) match {
-        case (Some(house: ThermalHouse), true, true) =>
+        case (Some(house: ThermalHouse), true, _) =>
           createThermalHouseResult(house)
         // We always want the results of the first tick
-        case (Some(house: ThermalHouse), _, false) =>
+        case (Some(house: ThermalHouse), _, true) =>
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala]: Why do we need these two cases? They will both return the same result.

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala [hunk 4]
```diff
@@ -534,12 +528,12 @@ final case class ThermalGrid(
...
         ),
-        state.tick != 0,
+        state.tick == 0,
       ) match {
-        case (Some(storage: CylindricalThermalStorage), true, true) =>
+        case (Some(storage: CylindricalThermalStorage), true, _) =>
           createCylindricalStorageResult(storage)
         // We always want the results of the first tick
-        case (Some(storage: CylindricalThermalStorage), _, false) =>
+        case (Some(storage: CylindricalThermalStorage), _, true) =>
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala]: Same as above.

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala [hunk 5]
```diff
@@ -493,24 +480,22 @@ class ThermalGridIT
...
       // Since this activation is caused by new weather data, we don't expect any
       // message for house or storage since there is no change of their operating
       // point nor one of it reached any boundary.
       resultListener.expectNoMessage()
-
       scheduler.expectMessage(Completion(heatPumpAgent, Some(26887)))
 
       /* TICK 26887
-        Storage will be empty
+        Heat storage is empty
```
Comment (staudtMarius) [inline src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:494]: Before, you changed is to `ThermalStorage`. Which one is correct?

**Review by staudtMarius — CHANGES_REQUESTED** [review]
Looks already quiete good. Just some small remarks from my side.

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala (hunk 5 above)
Comment (danielfeismann) [reply src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:494]: This is a heat storage, there is also the domestic hot water storage, both are ThermalStorages. So heat storage should be correct.

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala (hunk 3 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala]: We only would like to write a thermalResult either when 
- there is a change in the result (will be, if the qDot changes)
- in any case if we are at tick 0

Do you see a better option to achieve this?

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala (hunk 2 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala:321]: It could be possible here (and would work fine since `determineNextThreshold` handles both cases correct), but since this is only called by `handleCases` which only is called for feedIn, there won't be any negative qDot here.

I kept the qDotStorage scalaDoc unchanged since it is still valid and helps for understanding.

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala (hunk 3 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala]: Maybe we can write the condition as `lastOpThermals.forall(_.qDotHouse != currentOpThermals.qDotHouse) || state.tick == 0`.
With this, there would only be one case.

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala (hunk 5 above)
Comment (staudtMarius) [reply src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:494]: Ok. But then you should rename the `storage` in line 242, 990, 1239 and 1859 into `heat storage` as well.

File: src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala [hunk 6]
```diff
@@ -165,21 +165,19 @@ object CylindricalThermalStorage {
...
+    val maxEnergyThreshold = volumeToEnergy(
+      CubicMeters(
+        input.getStorageVolumeLvl.to(Units.CUBIC_METRE).getValue.doubleValue
+      ),
+      KilowattHoursPerKelvinCubicMeters(
+        input.getC
+          .to(PowerSystemUnits.KILOWATTHOUR_PER_KELVIN_TIMES_CUBICMETRE)
+          .getValue
+          .doubleValue
+      ),
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala]: In my opinion, it would be better to also move these two conversion to the utils class.

File: src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala [hunk 7]
```diff
@@ -243,4 +242,27 @@ object QuantityConversionUtils {
...
+      */
+    def toSquantsCelsius: squants.Temperature = Celsius(
+      quantity.to(CELSIUS).getValue.doubleValue
+    )
+
+    /** Returns a quantity with unit [[Kelvin]].
+      */
+    def toSquantsKelvin: squants.Temperature = Kelvin(
+      quantity.to(KELVIN).getValue.doubleValue
+    )
```
Comment (staudtMarius) [inline src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: Do we need the second method? If not, it can be removed and the first method could be renamed to `toSquants` like most of the conversion methods.

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala [hunk 8]
```diff
@@ -236,16 +235,15 @@ class ThermalGridIT
                 energy should equalWithTolerance(0.asMegaWattHour)
             }
         }
-
+      resultListener.expectNoMessage()
       scheduler.expectMessage(Completion(heatPumpAgent, Some(3416)))
 
       /* TICK 3416
-      Storage is fully heated up
+      ThermalStorage is fully heated up
```
Comment (staudtMarius) [inline src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala]: This could be renamed into `heat storage`. There are a few more such cases.

**Review by staudtMarius — CHANGES_REQUESTED** [review]
Some small questions.

File: src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala (hunk 6 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala]: To be honest, I won't do this since I guess we have this conversion only once at this place.

File: src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala (hunk 7 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: I remember that it was sometimes, no idea why, important to convert to Celsius or Kelvin. Therefor I guess we need both.

File: src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala (hunk 6 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala]: Ok. My idea was, that it would look cleaner. But we can leave it as it is now.

File: src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala (hunk 7 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: But we are using squants. We can convert the quantity to Kelvin, if we need it at some point.

Comment (danielfeismann) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: I see the danger, that someone will use this directly on Kelvin which the get's converted into Celsius. But let's see...

Comment (staudtMarius) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: There is only danger, if someone uses the `.value` method for a squants quantity. If we use the `toKelvin` method, then we will get the correct value.

File: src/test/scala/edu/ie3/util/quantities/QuantityConversionUtilsSpec.scala [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+import squants.thermal.{Celsius, Temperature}
+import tech.units.indriya.quantity.Quantities
+import tech.units.indriya.unit.Units.{CELSIUS, KELVIN}
+
+class QuantityConversionUtilsSpec extends UnitSpec {
+  implicit val doubleTolerance: Double = 1e-10
+  implicit val temperatureTolerance: Temperature = Celsius(1e-10)
+
+  "QuantityConversionUtils" should {
+    "properly convert from ComparableQuantity[Celsius] to squants temperatures and its double values" in {
```
Comment (staudtMarius) [inline src/test/scala/edu/ie3/util/quantities/QuantityConversionUtilsSpec.scala]: It is `Temperature` instead of `Celsius`.

**Review by staudtMarius — CHANGES_REQUESTED** [review]
One last thing.

File: src/test/scala/edu/ie3/util/quantities/QuantityConversionUtilsSpec.scala (hunk 9 above)
Comment (danielfeismann) [reply src/test/scala/edu/ie3/util/quantities/QuantityConversionUtilsSpec.scala]: True :)

**Review by staudtMarius — APPROVED** [review]
LGTM
