### PR TITLE
Fix determineModelBaseStateData for RandomLoadModel

### LINKED ISSUE #399: Fix determineModelBaseStateData for RandomLoadModel
Usage of random load profiles does not deliver results since there is no case for RandomLoadModel in determineModelBaseStateData

### LINKED ISSUE #401: Fix first non random profiles per typeday of random load profile
The first day per typeday (weekday, saturday, sunday) of random load profile doesn't seem random.

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #399 
resolves #401

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadModel.scala [hunk 1]
```diff
@@ -146,6 +145,7 @@ final case class RandomLoadModel(
       case Some(foundIt) => foundIt
       case None          =>
         /* Instantiate new gev distribution, put it to storage and return it */
+        val randomFactory = RandomFactory.get((Math.random() * 1000000).toInt)
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadModel.scala:148]: We can implement a 
`val randomFactory: RandomFactory = RandomFactory.get(42L)`
in the companion object so we don't need to set up individual factories for every load model

**Review by t-ober — CHANGES_REQUESTED** [review]
Thanks 🙂

**Review by t-ober — APPROVED** [review]
💯
