### PR TITLE
Fix negative required energy demand for thermalHouse

### LINKED ISSUE #1127: Fix negative required energy demand for thermalHouse
```
10:54:12.176 ERROR e.i.s.a.g.GridAgent$$anonfun$edu$ie3$simona$agent$grid$GridAgent$$initializing$1 - The possible 8.729442678011385E7 J or required -48773.219886155064 J amount of energy cannot be negative. This is not supported.
edu.ie3.simona.exceptions.InvalidParameterException: The possible 8.729442678011385E7 J or required -48773.219886155064 J amount of energy cannot be negative. This is not supported.
	at edu.ie3.simona.model.thermal.ThermalGrid$ThermalEnergyDemand$.apply(ThermalGrid.scala:606)
	at edu.ie3.simona.model.thermal.ThermalHouse.energyDemand(ThermalHouse.scala:133)
	at edu.ie3.simona.model.thermal.ThermalGrid.energyDemandAndUpdatedState(ThermalGrid.scala:84)
	at edu.ie3.simona.model.participant.HpModel.determineState(HpModel.scala:138)
	at edu.ie3.simona.model.participant.HpModel.determineFlexOptions(HpModel.scala:260)
	at edu.ie3.simona.model.participant.HpModel.determineFlexOptions(HpModel.scala:54)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.calculateFlexOptions(ParticipantAgentFundamentals.scala:694)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.calculateFlexOptions$(ParticipantAgentFundamentals.scala:678)
	at edu.ie3.simona.agent.participant.hp.HpAgent.calculateFlexOptions(HpAgent.scala:44)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.handleFlexRequest(ParticipantAgentFundamentals.scala:659)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.handleFlexRequest$(ParticipantAgentFundamentals.scala:653)
	at edu.ie3.simona.agent.participant.hp.HpAgent.handleFlexRequest(HpAgent.scala:44)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.checkForExpectedDataAndChangeState(ParticipantAgentFundamentals.scala:634)
	at edu.ie3.simona.agent.participant.ParticipantAgentFundamentals.checkForExpectedDataAndChangeState$(ParticipantAgentFundamentals.scala:557)
	at edu.ie3.simona.agent.participant.hp.HpAgent.checkForExpectedDataAndChangeState(HpAgent.scala:44)
	at edu.ie3.simona.agent.participant.ParticipantAgent$$anonfun$4.applyOrElse(ParticipantAgent.scala:383)
	at edu.ie3.simona.agent.participant.ParticipantAgent$$anonfun$4.applyOrElse(ParticipantAgent.scala:259)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at org.apache.pekko.actor.FSM.processEvent(FSM.scala:861)
	at org.apache.pekko.actor.FSM.processEvent$(FSM.scala:858)

```

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1127

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala [hunk 1]
```diff
@@ -147,9 +148,15 @@ final case class ThermalHouse(
...
   ): Energy = {
-    ethCapa * Kelvin(
+
+    val temperatureDelta =
       targetTemperature.toKelvinScale - startTemperature.toKelvinScale
-    )
+    val temperatureDiff =
+      if (temperatureDelta < 0)
+        Kelvin(0)
+      else Kelvin(temperatureDelta)
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala:157]:
```suggestion
    val temperatureDiff =
      Kelvin(targetTemperature.toKelvinScale - startTemperature.toKelvinScale)
        .max(Kelvin(0))
```

**Review by sebastian-peter — APPROVED** [review]
Thanks for the quick fix! I adapted the ScalaDoc comment a tiny bit, please go ahead and merge this if it's fine to you
