### PR TITLE
Fix ConfigFailFastSpec after Refsystem passing

### LINKED ISSUE #797: VnSimona breaks with optional RefSystem passing
with changing the voltage level abbreviations to english terms (LV,MV,HV,EHV) when introducing #780 VnSimona breaks.
ConfigFailFastSpec need to be updated as well

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #797

### CODE REVIEW

**Comment by staudtMarius** [comment]
@danielfeismann Is there a reason for changing the config template?

**Comment by danielfeismann** [comment]
Imho, if we want to have the refsystem only optional in config, we need to adapt this. I didn't saw that in my review. But maybe misunderstood something here...

**Comment by staudtMarius** [comment]
The point of #780 was to make the line in the config optional. If the user does not want to specify the refsystem, then a default one should be used. Therefore I adapted the config template.

**Comment by danielfeismann** [comment]
Right. But there are any changes of 'config-template.conf' in #780. Thus I started this PR. Need to fix some more things and will come back to you then.

File: src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala [hunk 1]
```diff
@@ -431,67 +432,71 @@ case object ConfigFailFast extends LazyLogging {
...
 
-    val voltLvls =
-      refSystem.voltLvls.getOrElse(List.empty[SimonaConfig.VoltLvlConfig])
-    val gridIds = refSystem.gridIds.getOrElse(List.empty[String])
+  private def checkRefSystem(refSystems: List[RefSystemConfig]): Unit = {
+    refSystems.foreach { refSystem =>
+      {
+        val voltLvls =
+          refSystem.voltLvls.getOrElse(List.empty[SimonaConfig.VoltLvlConfig])
+        val gridIds = refSystem.gridIds.getOrElse(List.empty[String])
```
Comment (t-ober) [inline src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala:441]: Why do I need to pass a grid id ?
Can't we just define a default refsystem for all sensible voltage level and use that.
My goal is that the user does not even need to worry what a ref system is.

**Review by t-ober — CHANGES_REQUESTED** [review]

File: src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala (hunk 1 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala:441]: This will check the grid id when the users provide a RefSystem, just as it does in the past. You want to remove the ability to specify a RefSystem via config completely and not just make it optional?

Comment (t-ober) [reply src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala:441]: whoops. you are right slightly misread it. that gets only run if a refsystem is actually defined

**Review by t-ober — CHANGES_REQUESTED** [review]
Looks good to me. You might take a short look at the sonarqube complaints. We could at least get rid of that unused variable.

**Review by t-ober — APPROVED** [review]
