### PR TITLE
Fixing duration calculation in result events.

### LINKED ISSUE #801: Fixing duration calculation in result events
duration calculation should return duration for the simulation step. At the moment it returns the total duration from start till the end of each step

```
11:40:00.182 INFO  e.i.s.e.l.RuntimeEventListener$ - ******* Simulation until 2019-01-01T19:00:00Z completed. (duration: 0h : 0m : 27s , memory: 0.1 GB) ******
11:40:01.452 INFO  e.i.s.e.l.RuntimeEventListener$ - ******* Simulation until 2019-01-01T20:00:00Z completed. (duration: 0h : 0m : 28s , memory: 0.2 GB) ******
11:40:02.708 INFO  e.i.s.e.l.RuntimeEventListener$ - ******* Simulation until 2019-01-01T21:00:00Z completed. (duration: 0h : 0m : 29s , memory: 0.1 GB) ******
11:40:03.989 INFO  e.i.s.e.l.RuntimeEventListener$ - ******* Simulation until 2019-01-01T22:00:00Z completed. (duration: 0h : 0m : 30s , memory: 0.1 GB) ******
```

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #801

### CODE REVIEW

**Review by danielfeismann — APPROVED** [review]
LGTM!

File: src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala [hunk 1]
```diff
@@ -26,6 +27,7 @@ import java.time.ZonedDateTime
 final case class RuntimeEventLogSink(
     simulationStartDate: ZonedDateTime,
     log: Logger,
+    private var last: Long = 0L,
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala:30]: Using `var` is usually not what we want, but rather immutable values. We should look into this and try to find such a solution.
