### PR TITLE
Fix unreachable code

### LINKED ISSUE #167: Fix unreachable code
https://github.com/ie3-institute/simona/blob/1d5dcb7e72fac0eb0296e2dc4145ff3ed55806f0/src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala#L304-L307

Introduced with #77. Statements have to be switched. Also, a test for this is required.

https://simona.ie3.e-technik.tu-dortmund.de/sonar/project/issues?id=edu.ie3%3Asimona&issues=AX5EWrTicE05oj4IaDLM&open=AX5EWrTicE05oj4IaDLM

### PR DESCRIPTION
**Pull request by danielfeismann**
resolve #167

### CODE REVIEW

**Comment by sebastian-peter** [comment]
While reviewing, I found that we have the same issue of non-wrapped exceptions thrown just a couple lines above:
https://github.com/ie3-institute/simona/blob/6125fa9726b540a6ddf54ab76621d2ab6d915d1e/src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala#L116-L122

I implemented a solution here, let me know what you think: https://github.com/ie3-institute/simona/compare/df/%23167-fix-unreachable-code...sp/%23167-ResultEventListener-suggestion 
If you think these changes are helpful, feel free to just fast-forward this branch to mine.

**Comment by sebastian-peter** [comment]
That being said, I also found another weak spot of this implementation, revealed by the new test.

Since initialization is started within `preStart()`, there is a chance that initialization crashes before the creator of this listener even has the chance to `watch()` its child. This means there's a chance that we don't even notice the initialization crashing.

https://github.com/ie3-institute/simona/blob/6125fa9726b540a6ddf54ab76621d2ab6d915d1e/src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala#L152-L153

File: src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala [hunk 1]
```diff
@@ -287,10 +295,6 @@ class ResultEventListener(
       stash()
       stay()
 
-    case Event(baseData: BaseData, UninitializedData) =>
-      unstashAll()
-      goto(Idle) using baseData
-
     case Event(Init, _) =>
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:298]: What's the reasoning behind this deletion?

File: src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala [hunk 2]
```diff
@@ -299,18 +303,20 @@ class ResultEventListener(
...
+    case Event(SinkResponse(classToSink), _) =>
+      // Sink Initialization succeeded
+      log.debug("Initialization complete!")
+      supervisor ! ServiceInitComplete
+
+      unstashAll()
+      goto(Idle) using BaseData(classToSink)
+
+    case Event(Status.Failure(ex), _) =>
+      throw new InitializationException("Unable to setup SimonaSim.", ex)
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:319]: Maybe an additional logging statement with the exception could be slightly more verbose here?

**Review by johanneshiry — APPROVED** [review]
LGTM thank you! :-)

Please consider taking into account my questions and comments if you want to. But these are only of minor concern.

File: src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala [hunk 3]
```diff
@@ -141,6 +137,22 @@ class ResultEventListenerSpec
         assert(outputFile.exists)
         assert(outputFile.isFile)
       }
+
+      "check if actor dies when it should die" in {
+        val fileHierarchy = resultFileHierarchy(1, ".ttt")
```
Comment (t-ober) [inline src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala:142]:
```suggestion
        val fileHierarchy = resultFileHierarchy(5, ".ttt")
```

Comment (t-ober) [reply src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala:142]: Since the specific runid is used for a `ResultFileHierarchy` at line 121 the test can fail since the directory that should be created already exists. As the direcetory that is created uses the runid passed to the `resultFileHierarchy` for naming using a different id solves the problem

**Review by t-ober — CHANGES_REQUESTED** [review]
Looks good - this pipe thing is cool. Please have a look at the ResultFileHierarchy naming issue though

File: src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala (hunk 3 above)
Comment (sebastian-peter) [reply src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala:142]: Already fixed this in the branch I mentioned [here](https://github.com/ie3-institute/simona/pull/171#issuecomment-1065615202)

File: src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala (hunk 1 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:298]: This has become obsolete due to the result of the sink initialization now being piped to itself

File: src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala (hunk 2 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:321]: Good point, please have a look again

Comment (ckittl) [reply src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:322]: There also is a logging statement in the defined supervision strategy. We might have a look, if this is not double the work, then.

Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala:321]: seems it would log twice

```
      case ex: Exception =>
        self ! EmergencyShutdownInitiated
        logger.error(
          "The simulation's guardian received an uncaught exception. - {}: \"{}\" - Start emergency shutdown.",
          ex.getClass.getSimpleName,
          ex.getMessage
        )
```

**Review by t-ober — APPROVED** [review]

**Review by ckittl — APPROVED** [review]
