### PR TITLE
Fixed pekko config not written as output

### LINKED ISSUE #1302: Fix pekko config output
Currently, the pekko config is not written ín the output config.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1302

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala [hunk 1]
```diff
@@ -225,13 +226,16 @@ trait SetupHelper extends LazyLogging {
...
     * [[SimonaConfig]], otherwise an exception is thrown
     *
+    * @param typeSafeConfig
+    *   All configuration parameters
     * @param simonaConfig
-    *   the configuration file
+    *   The configuration for SIMONA
     * @return
-    *   the resulting result file hierarchy
+    *   The resulting result file hierarchy
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala:234]: Our new formatting rules also include full stops at the end of text lines, so it'd look something like this: 

```suggestion
    * [[SimonaConfig]], otherwise an exception is thrown.
    *
    * @param typeSafeConfig
    *   All configuration parameters.
    * @param simonaConfig
    *   The configuration for SIMONA.
    * @return
    *   The resulting result file hierarchy.
```

Just something I wanted to mention, because then the format does not have to be touched again :)

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
One tiny point, otherwise LGTM
