### PR TITLE
Fix variable shadowing.

### LINKED ISSUE #1371: Solve VariableShadowing code smells
Should be easily solvable. List [here](https://simona.ie3.e-technik.tu-dortmund.de/sonar/project/issues?resolved=false&rules=external_scapegoat%3Acom.sksamuel.scapegoat.inspections.VariableShadowing&id=edu.ie3%3Asimona)

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolve #1371.

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala [hunk 1]
```diff
@@ -121,19 +121,19 @@ final case class ThermalHouse(
...
     * @param startTemperature
     *   The starting temperature.
     * @return
     *   The needed energy to change.
     */
   private def energy(
-      targetTemperature: Temperature,
+      target: Temperature,
       startTemperature: Temperature,
   ): Energy = {
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala]: Maybe we simply remove the targettemperature here? Since it should always be the target... I would prefer to rename this method in that case to `energyToReachTargetTemperature()` or similar.

File: src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala [hunk 2]
```diff
@@ -41,25 +41,31 @@ class CylindricalThermalStorageSpec
...
+          .to(Units.CELSIUS)
+          .getValue
+          .doubleValue()
       ),
       Celsius(
-        storageInput.getReturnTemp.to(Units.CELSIUS).getValue.doubleValue()
+        cylindricalStorageInput.getReturnTemp
+          .to(Units.CELSIUS)
+          .getValue
+          .doubleValue()
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala]: toSquants? :)

File: src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala [hunk 3]
```diff
@@ -41,25 +41,31 @@ class CylindricalThermalStorageSpec
...
   ): CylindricalThermalStorage = {
     val storedEnergy = CylindricalThermalStorage.volumeToEnergy(
       volume,
       KilowattHoursPerKelvinCubicMeters(
-        storageInput.getC
+        cylindricalStorageInput.getC
           .to(PowerSystemUnits.KILOWATTHOUR_PER_KELVIN_TIMES_CUBICMETRE)
           .getValue
           .doubleValue
       ),
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala]: Ok I got convinced. With #1358 there will also conversion to squants. Feel free to pick it from there.

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala [hunk 4]
```diff
@@ -51,13 +51,13 @@ import scala.jdk.OptionConverters.RichOptional
   *
   * @param gridAgentContext
   *   ActorContext of the grid agent
-  * @param environmentRefs
+  * @param _environmentRefs
   *   The environment refs
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala]: Not sure what is my opinion here. Maybe @sebastian-peter has a good idea?

**Review by danielfeismann — DISMISSED** [review]
Some thoughts from my side

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala (hunk 4 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala]: With #1373 this class will be converted to an object. So my fix will only be used until #1373 is merged.

File: src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala [hunk 5]
```diff
@@ -277,4 +278,27 @@ object QuantityConversionUtils {
...
+
+  /** Implicit class that contains a method to convert a given
+    * [[ComparableQuantity]] with unit
+    * [[KILOWATTHOUR_PER_KELVIN_TIMES_CUBICMETRE]] into
+    * [[edu.ie3.util.scala.quantities.KilowattHoursPerKelvinCubicMeters]].
+    *
+    * @param quantity
+    *   To convert.
+    */
+  implicit class SpecificHeatCapacityConversionSimona(
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: Thanks for providing this new implementation. You could also use it in `CylindricalThermalStorage`.

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala (hunk 4 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala]: Resolved!

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
One more suggestion from my side :)

File: src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala (hunk 5 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: Marius [suggested to do so](https://github.com/ie3-institute/simona/pull/1399/files/c91da6a814ae9f9eb12236de318445a6aa265c41#diff-138235cf460839028f38675ad6ec2ac4b045c0904bb4d8ff4f25eb0072f1b215) I blocked that first, but got convinced later here. So please feel free to complete this within this PR @staudtMarius

Comment (sebastian-peter) [reply src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala]: Ah, got it. So, since it exists now, it could be used here as well :)

**Review by sebastian-peter — APPROVED** [review]
LGTM thanks!
