### PR TITLE
Fixing unreliable `RuntimeEventListenerSpec`

### LINKED ISSUE #709: Fix or disable randomly failing test in `RuntimeEventListenerSpec`
Testing the log messages is super unreliable and randomly fails in CI.

Try to find out why, and if it is not fixable, disable the test (`ignore`)

```
- must return valid log messages for each status event *** FAILED *** (111 milliseconds)
  java.lang.AssertionError: Received 1 excess messages on LoggingTestKitImpl(1,Some(INFO),None,None,Some(Initializing Agents and Services for Simulation ... ),None,None,Map(),true,None).
  at org.apache.pekko.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:115)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$5(RuntimeEventListenerSpec.scala:154)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$5$adapted(RuntimeEventListenerSpec.scala:150)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$4(RuntimeEventListenerSpec.scala:150)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  ...
```

### PR DESCRIPTION
**Pull request by sebastian-peter**
Closes #709

I also fixed some other unreliable tests and/or improved unspecific failure messages

### CODE REVIEW

File: src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala [hunk 1]
```diff
@@ -340,7 +340,7 @@ class LoadModelScalingSpec extends UnitSpec with TableDrivenPropertyChecks {
         getRelativeDifference(
           quantile95,
           targetMaximumPower,
-        ) should be < Percent(1d)
+        ) should be < Percent(2d)
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala:343]: Do we increase this because even the 95 quantile sometimes exceed one percent?

**Review by danielfeismann — CHANGES_REQUESTED** [review]
LGTM just a minor question

File: src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala (hunk 1 above)
Comment (sebastian-peter) [reply src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala:343]: Yes. I redruced the sample size from ten years to one year recently, and I tested it 20-30 times, but that wasn't enough apparently.

**Review by danielfeismann — APPROVED** [review]
LGTM
