### PR TITLE
Enhancing DBFS tests with checking result outputs via listeners.

### LINKED ISSUE #269: Enhance DBFS tests with checking result outputs via listeners
Currently, power flow results are not checked by the DBFS tests. Enhance `DBFSAlgorithmCenGridSpec`/`DBFSAlgorithmSupGridSpec` so that result events are received and tested. Also test the handling of failed power flows which happened in the tested sub grid or in some other sub grid (via `FailedPowerFlow` message).

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #269

### CODE REVIEW

File: src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala [hunk 1]
```diff
@@ -62,30 +64,35 @@ class DBFSAlgorithmSupGridSpec
     with ImplicitSender
     with DbfsTestGrid {
 
+  private val scheduler: TestProbe = TestProbe("scheduler")
+  private val primaryService: TestProbe = TestProbe("primaryService")
+  private val weatherService: TestProbe = TestProbe("weatherService")
+  private val hsActor: TestProbe = TestProbe("hsActor")
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala:70]: You probably use `hs` as an abbreviation for Hochspannung? In this case please use `hv` for high voltage instead, please

File: src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala [hunk 2]
```diff
@@ -198,23 +216,33 @@ class DBFSAlgorithmSupGridSpec
...
+                      value.getvAng().getValue shouldBe 0
+                  }
+
+                  powerFlowResultEvent.lineResults shouldBe empty
+                  powerFlowResultEvent.switchResults shouldBe empty
+                  powerFlowResultEvent.transformer2wResults shouldBe empty
+                  powerFlowResultEvent.transformer3wResults shouldBe empty
+              }
+
+              hsActor.expectMsgPF() { case FinishGridSimulationTrigger(3600) =>
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala:243]: Here, you can use `expectMsg` instead (you're not making use of the partial function)

File: src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala [hunk 3]
```diff
@@ -334,24 +370,34 @@ class DBFSAlgorithmSupGridSpec
...
+                  powerFlowResultEvent.nodeResults.headOption match {
+                    case Some(value) =>
+                      value.getvMag().getValue shouldBe 1
+                      value.getvAng().getValue shouldBe 0
+                  }
+
+                  powerFlowResultEvent.lineResults shouldBe empty
+                  powerFlowResultEvent.switchResults shouldBe empty
+                  powerFlowResultEvent.transformer2wResults shouldBe empty
+                  powerFlowResultEvent.transformer3wResults shouldBe empty
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala:395]: Maybe it's worthwhile to adapt the `simonaConfig` (or rather, adapt a copy of it) so that power flow grid results are sent. `simona.output.grid` should be the right place

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Great job! I especially like the extensive commenting you did on the tests, which will for sure come in handy when others (or you yourself ;) ) will be trying to (again) understand the underlying processes here.

As usual, I have some comments, of which most of them you will surely solve quite quickly.

File: src/test/scala/edu/ie3/simona/agent/grid/DBFSGridAgents.scala [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+import edu.ie3.simona.ontology.messages.VoltageMessage.{
+  ProvideSlackVoltageMessage,
+  RequestSlackVoltageMessage
+}
+import edu.ie3.simona.test.common.UnitSpec
+
+import java.util.UUID
+import scala.concurrent.duration.DurationInt
+
+trait DBFSGridAgents extends UnitSpec {
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/DBFSGridAgents.scala:26]: `DBFSMockGridAgents` would be a more expressive name. Also, ScalaDoc for this trait (short description) would be nice

File: src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala [hunk 5]
```diff
@@ -0,0 +1,275 @@
...
+      // normally the slack node would send a FinishGridSimulationTrigger to all
+      // connected inferior grids, because the slack node is just a mock, we imitate this behavior
+      superiorGridAgent.gaProbe.send(
+        centerGridAgent,
+        FinishGridSimulationTrigger(3600)
+      )
+
+      // after a FinishGridSimulationTrigger is send the inferior grids, they themselves will send the
+      // Trigger forward the trigger to their connected inferior grids. Therefore the inferior grid
+      // agent should receive a FinishGridSimulationTrigger
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala:253]: That's still not the way it's supposed to be

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
We're almost there! Thanks for contributing these improvements, again
