### PR TITLE
Fix grammar and spelling in docs and comments

### LINKED ISSUE #1021: Fix grammar and spelling in docs and comments

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1021

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala [hunk 1]
```diff
@@ -388,7 +388,7 @@ protected trait ParticipantAgentFundamentals[
 
   /** Assume we have information, that are available in a fixed resolution after
     * each full hour (including the full hour), then we have to determine, at
-    * what first tick those information are available.
+    * what first tick this information are available.
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala:391]: these

File: src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala [hunk 2]
```diff
@@ -132,10 +132,10 @@ protected trait FixedFeedInAgentFundamentals
     val lastTickInSimulation = simulationEndDate.toTick(simulationStartDate)
     val dataTicks =
       /* As participant agents always return their last known operation point on request, it is sufficient
-       * to let a fixed fixed in model determine it's operation point on:
+       * to let a fixed model determine its operation point on:
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala:135]: FixedFeedIn model?

File: src/main/scala/edu/ie3/simona/main/RunSimona.scala [hunk 3]
```diff
@@ -86,7 +86,7 @@ trait RunSimona[T <: SimonaSetup] extends LazyLogging {
     }
   }
 
-  /** Method to be implemented to setup everything that is necessary for a
+  /** Method to be implemented to set up everything that is necessary for a
     * simulations. This is by creating an instance of [[SimonaSetup]]
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/main/RunSimona.scala:90]: Another one...

File: src/main/scala/edu/ie3/simona/model/SystemComponent.scala [hunk 4]
```diff
@@ -40,7 +40,7 @@ abstract class SystemComponent(
 
   private val elementType: String = this.getClass.getSimpleName
 
-  // check if a uuid is provided
+  // check if an uuid is provided
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/model/SystemComponent.scala:43]: I think `a` is correct here, since _pronounciation_ counts, and UUID sounds like "you-you-i-d". [Wikipedia agrees.](https://en.wikipedia.org/wiki/Universally_unique_identifier)

File: src/test/scala/edu/ie3/simona/test/common/model/grid/SubGridGateMokka.scala [hunk 5]
```diff
@@ -21,14 +21,14 @@ import org.scalatestplus.mockito.MockitoSugar
...
-  /** Mocks a node with it's basic needed information
+  /** Mocks a node with its basic needed information
     *
     * @param uuid
     *   Unique identifier of the node
     * @param subnet
     *   Sub net number
     * @return
-    *   [[NodeInput]] with these information
+    *   [[NodeInput]] with this information
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/test/common/model/grid/SubGridGateMokka.scala:31]: "information" can also mean plural, not necessarily wrong imho

**Review by sebastian-peter — CHANGES_REQUESTED** [review]

File: src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala (hunk 1 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala:391]: > 'this information' is grammatically correct because 'information' is an uncountable noun.
by Google 😄

File: src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala (hunk 2 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala:135]: Oh yes, that could be true. Will change it

File: src/test/scala/edu/ie3/simona/test/common/model/grid/SubGridGateMokka.scala (hunk 5 above)
Comment (danielfeismann) [reply src/test/scala/edu/ie3/simona/test/common/model/grid/SubGridGateMokka.scala:31]: see above. But I'm not sure and I'll not insists to it.

File: src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala (hunk 1 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala:391]: Ok then :)

File: src/main/scala/edu/ie3/simona/main/RunSimona.scala (hunk 3 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/main/RunSimona.scala:90]: Good catch!

**Review by sebastian-peter — APPROVED** [review]
Thanks!
