### PR TITLE
Removing config of vn_146_lv_small

### LINKED ISSUE #290: Broken config of vn_146_lv_small

### PR DESCRIPTION
**Pull request by vickybung1**
Resolves #290

### CODE REVIEW

**Comment by sebastian-peter** [comment]
Ok upon inspection of the results that we get from this grid I realized there are no system participants connected whatsoever, so there is no power flow happening and we get no output that one could use for anything.
Given this fact @t-ober and I decided that it would probably be best to just remove this sample grid from the SIMONA code base alltogether, which will reduce overall maintenance needs. So could you please just delete the whole vn_146 grid directory and commit? Thanks!

File: src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala [hunk 1]
```diff
@@ -17,6 +17,7 @@ import edu.ie3.simona.ontology.messages.SchedulerMessage.{
   SimulationFailureMessage,
   SimulationSuccessfulMessage
 }
+
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala:20]: Also please revert this :)

**Review by sebastian-peter — APPROVED** [review]
Thanks, all good now
