### PR TITLE
Fixed handling of power flow results in `ResultServiceProxy`

### LINKED ISSUE #1679: Fix power flow result handling in `ResultServiceProxy`
There is a bug in the handling of power flow result that contains congestion results.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1679

### CODE REVIEW

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 1]
```diff
@@ -75,8 +71,6 @@ object ResultServiceProxy {
     *   The current tick of the result proxy.
     * @param threeWindingResults
     *   A map that contains partial three-winding transformer results.
-    * @param gridResults
-    *   A map: uuid to grid results.
     * @param results
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:84]: do results now include the gird results? If not, maybe we should rename reults to participantResults?

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 2]
```diff
@@ -98,20 +92,23 @@ object ResultServiceProxy {
         Transformer3wKey,
         AggregatedTransformer3wResult,
       ] = Map.empty,
-      gridResults: Map[UUID, ResultEntity] = Map.empty,
-      results: Map[UUID, Iterable[ResultEntity]] = Map.empty,
+      results: Map[UUID, Map[Class[? <: ResultEntity], ResultEntity]] =
+        Map.empty,
       waitingForResults: Map[UUID, Long] = Map.empty,
+      noUpdate: Set[UUID] = Set.empty,
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: ScalaDoc.

Maybe rename since it could be interpreted as "number of some Update"

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 3]
```diff
@@ -194,41 +197,52 @@ object ResultServiceProxy {
...
-      val updatedResults = results.get(uuid) match {
-        case Some(values) =>
-          val updatedValues = values
-            .map { value => value.getClass -> value }
-            .toMap
-            .updated(result.getClass, result)
-            .values
-
-          results.updated(uuid, updatedValues)
+      val (updatedResults, changedResults) = results.get(uuid) match {
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: To me, naming is misleading. An update is also a change, right.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 4]
```diff
@@ -454,4 +486,51 @@ object ResultServiceProxy {
     }
   }
 
+  /** Compares the new results to the old results. If a new result does not
+    * match any old result, the new result is returned.
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]:
```suggestion
  /** Compares the new results with the old ones. If a new result does not match any of the 
  * old  results, the new result is returned.
```

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 5]
```diff
@@ -454,4 +486,51 @@ object ResultServiceProxy {
...
+    *
+    * @param results
+    *   To compare.
+    * @param oldResults
+    *   For comparison.
+    * @return
+    *   The updated results.
+    */
+  private[results] def filterUnchangedResults(
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: What does it do? Return only unchangedResults? Or return unchanged results plus new ones? To me ScalaDoc and method naming do not match.

Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: Same below

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 3 above)
Comment (danielfeismann) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: Ok got it. Its boolean. What about `hasResultChanged`?

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 6]
```diff
@@ -194,41 +197,52 @@ object ResultServiceProxy {
...
 
         case None =>
-          results.updated(uuid, Iterable(result))
+          (results.updated(uuid, Map(result.getClass -> result)), true)
+      }
+
+      val updated = if changedResults then {
+        noUpdate.excl(uuid)
+      } else {
+        noUpdate.incl(uuid)
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: again not sure if this is a proper naming

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 7]
```diff
@@ -194,41 +197,52 @@ object ResultServiceProxy {
...
+      *
       * @param uuids
       *   For which results should be returned.
       * @return
       *   A map: uuid to results.
       */
-    def getResults(uuids: Seq[UUID]): Map[UUID, Iterable[ResultEntity]] = {
+    def getResults(
+        uuids: Seq[UUID],
+        sendUnchangedResults: Boolean,
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:272]: Scaladoc

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 8]
```diff
@@ -194,41 +197,52 @@ object ResultServiceProxy {
...
+    ): Map[UUID, List[ResultEntity]] = {
       uuids.flatMap { uuid =>
-        gridResults.get(uuid) match {
-          case Some(values) =>
-            Some(uuid -> Iterable(values))
-          case None =>
-            results.get(uuid).map { res => uuid -> res }
-        }
+        if !noUpdate.contains(uuid) || sendUnchangedResults then {
+          // we only sent result, if either there was an update or we explicitly requested to send unchanged results
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:276]: Is there a case / what will be the case where we explicitly request to send unchanged results? Thinking about if we really need this case here.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 9]
```diff
@@ -338,43 +357,55 @@ object ResultServiceProxy {
...
-            oldResults.get(model) match {
-              case Some(oldResult) =>
-                // Temporarily change time for comparison, then revert
-                val oldTime = oldResult.getTime
-                oldResult.setTime(res.getTime)
-                val equal = oldResult == res
-                oldResult.setTime(oldTime)
-
-                if equal then None else Some(model -> res)
+      val (updatedResults, changedResults, notUpdated) =
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: updatedResults seems to be allResults right? Thus renaming it?

**Review by danielfeismann — CHANGES_REQUESTED** [review]
Thanks for fixing this bug. However some things are not fully clear to me, please have a look if there are possibilites for improvements

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 1 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:84]: `results` now include all results.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 8 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:276]: I am using this with simosaik. There I need an option to request all results.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 10]
```diff
@@ -98,20 +94,23 @@ object ResultServiceProxy {
         Transformer3wKey,
         AggregatedTransformer3wResult,
       ] = Map.empty,
-      gridResults: Map[UUID, ResultEntity] = Map.empty,
-      results: Map[UUID, Iterable[ResultEntity]] = Map.empty,
+      results: Map[UUID, Map[Class[? <: ResultEntity], ResultEntity]] =
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:107]: Does the `Map[Class[? <: ResultEntity], ResultEntity]` ever have more than one entry? If not, this could be way simpler...

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 11]
```diff
@@ -338,43 +361,55 @@ object ResultServiceProxy {
...
-
-                if equal then None else Some(model -> res)
+      val (allResults, changedResults, notUpdated) =
+        (transformer3wResults ++ nodeResults ++ switchResults ++ lineResults ++ transformer2wResults ++ congestionResults)
+          .groupBy(_.getInputModel)
+          .foldLeft(
+            stateData.results,
+            Map.empty[UUID, Seq[ResultEntity]],
+            Seq.empty[UUID],
+          ) { case ((allResults, changed, notChanged), (model, results)) =>
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: Do we now have to concat seven maps, re-group them, and fold over all entities every time we receive a new result? Maybe there's a more performant way to do this...

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 10 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:107]: For the participants we have the results and maybe flex options. For the nodes, lines and transformers we have their results and maybe congestion results.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 12]
```diff
@@ -454,4 +490,51 @@ object ResultServiceProxy {
...
+
+  /** Compares the new result to the old results. If a new result matched any
+    * old result, the new result is returned.
+    *
+    * @param result
+    *   To compare.
+    * @param oldResults
+    *   For comparison
+    * @return
+    *   An option for the changed result or None.
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: Please enhance the scaladoc a bit... For example, `result` is supposed to be the new result, right?

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 10 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:107]: Ah, got it

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala (hunk 11 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala]: We have to check all new results. But I will try to find a faster way of doing it.

File: src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala [hunk 13]
```diff
@@ -369,40 +395,41 @@ object ResultServiceProxy {
...
       val (allResults, changedResults, notUpdated) =
         (transformer3wResults ++ nodeResults ++ switchResults ++ lineResults ++ transformer2wResults ++ congestionResults)
-          .groupBy(_.getInputModel)
           .foldLeft(
             stateData.results,
-            Map.empty[UUID, Seq[ResultEntity]],
+            Seq.empty[ResultEntity],
             Seq.empty[UUID],
-          ) { case ((allResults, changed, notChanged), (model, results)) =>
+          ) { case ((allResults, changed, notChanged), result) =>
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/service/results/ResultServiceProxy.scala:410]: Variable shadowing of `allResults`

File: src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentInitSpec.scala [hunk 14]
```diff
@@ -84,12 +84,11 @@ class ParticipantAgentInitSpec
 
         val scheduler = createTestProbe[SchedulerMessage]()
 
-        val gridAgent = createTestProbe[GridAgent.Message]()
         val primaryService = createTestProbe[PrimaryServiceProxy.Message]()
-        val resultServiceProxy = createTestProbe[ResultEvent | ExpectResult]()
+        val resultServiceProxy =
+          createTestProbe[ResultEvent | ExpectResult | NoResult]()
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentInitSpec.scala]: This is just cosmetics, but maybe it'd make sense to create a type `ResultProviderMessage` (or something better) that unions these types, maybe within ResultServiceProxy?

File: src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala [hunk 15]
```diff
@@ -208,36 +220,66 @@ class ResultServiceProxySpec
 
     "correctly handle unchanged grid result" in {
       val listener = TestProbe[ResultResponse]("listener")
+      val resultProvider = TestProbe[ResultResponse]("listener")
 
       val resultProxy =
-        spawn(ResultServiceProxy(Seq(listener.ref), startTime, 10))
+        spawn(ResultServiceProxy(Seq(listener.ref), dummyTime, 10))
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala]: Why change this?

File: src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala:1]: You can now remove ConfigTestData from the inheritance list of the test class... Which is a good thing imho

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Looks good! I only have comments that should be quick to solve this time ;)

File: src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala (hunk 15 above)
Comment (staudtMarius) [reply src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala]: We are using the dummy time for the results. The `startTime` is completly different from the dummy timestamp.

Comment (sebastian-peter) [reply src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala]: Yes, but you're setting the parameter `simStartTime` here, not the result times. For all other test cases here you're using `startTime`, which still works here as well.

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala [hunk 16]
```diff
@@ -112,11 +112,13 @@ object GridAgent extends DBFSAlgorithm with DCMAlgorithm {
       buffer: StashBuffer[Message],
   ): Behavior[Message] = Behaviors.receivePartial {
     case (ctx, doPowerFlowTrigger: DoPowerFlowTrigger) =>
-      // inform the result proxy that this grid agent will send new results
-      constantData.environmentRefs.resultProxy ! ExpectResult(
-        gridAgentBaseData.assets,
-        doPowerFlowTrigger.tick,
-      )
+      if doPowerFlowTrigger.tick >= constantData.resolution then {
```
Comment (sebastian-peter) [inline src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala]: This now prevents `ExpectResults` to be sent early in the simulation..?

**Review by sebastian-peter — CHANGES_REQUESTED** [review]

File: src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/simona/service/results/ResultServiceProxySpec.scala:1]: Also, unused import now

File: src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala (hunk 16 above)
Comment (staudtMarius) [reply src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala]: That was a work around. I don't think it is necessary anymore. I will remove it.

**Review by sebastian-peter — DISMISSED** [review]

File: src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala [hunk 17]
```diff
@@ -286,7 +289,8 @@ class EmAgentIT
         )
 
         // we receive update messages, since new set points were provided
-        resultServiceProxy.receiveMessages(2) should contain allOf (
+        resultServiceProxy.receiveMessages(3) should contain allOf (
+          NoResult(storageInput.getUuid, 7200),
           ExpectResult(pvInput.getUuid, 7200),
           ExpectResult(storageInput.getUuid, 7200)
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala:296]: How can we expect NoResult and ExpectResult from the storage in the same tick?

Comment (danielfeismann) [reply src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala:296]: Or is it because of the new setPoint?

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala [hunk 18]
```diff
@@ -2967,14 +2966,11 @@ class ThermalGridIT
         )
       }
 
-      // expect messages due to flex activation
-      resultServiceProxy.receiveMessages(2) should contain allOf (
+      resultServiceProxy.receiveMessages(4) should contain allOf (
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:2969]: what is the fourth message we expect?

**Review by danielfeismann — CHANGES_REQUESTED** [review]

File: src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala (hunk 17 above)
Comment (staudtMarius) [reply src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala:296]: Yes. First we don't have to calculate a new result and therefore, we expect no result. After we receive new data, we expect a result.

Comment (danielfeismann) [reply src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala:296]: Ok, maybe a comment similar to ThermalGridIT makes sense here as well?

File: src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala (hunk 18 above)
Comment (staudtMarius) [reply src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:2969]:
```
      resultServiceProxy.receiveMessages(4) should contain allOf (
        // expect messages due to flex activation
        ExpectResult(typicalHpInputModel.getUuid, 27500, true),
        ExpectResult(pvInput.getUuid, 27500, true),
        // expect messages due to new set point
        ExpectResult(typicalHpInputModel.getUuid, 27500),
        ExpectResult(pvInput.getUuid, 27500)
      )
```
We are checking four messages here,

Comment (danielfeismann) [reply src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala:2969]: Nevermind, thanks!

**Review by danielfeismann — APPROVED** [review]
