### PR TITLE
Fixed bugs in congestion management.

### LINKED ISSUE #1393: Fix bug in returned next tick after congestion management
Currently, the grid agent returns the current tick as next tick after finishing the congestion management.

### LINKED ISSUE #1395: Fix bug in CongestionResult values
The returned value of the `CongestionResult` should be given in percent. For lines and transformers the value is currently given in percent/100.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1393
Resolves #1395

### CODE REVIEW

File: src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        behaviorWithContextAndBuffer { (ctx, buffer) =>
+          GridAgent.finishCongestionManagement(
+            stateData,
+            ctx,
+          )(using constantData, buffer)
+        }
+      )
+
+      // we should receive an empty result event
+      resultListener.expectMessageType[PowerFlowResultEvent]
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala]: I like the idea to get an information that the congestion management has finished. On the other hand, we normally don't send empty messages, right? Also an empty message could have two interpretations, a) process is finished, b) something went wrong.

File: src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+}
+
+class DCMAlgorithmSpec
+    extends ScalaTestWithActorTestKit
+    with UnitSpec
+    with CongestionTestBaseData {
+
+  "The DCMAlgorithm" should {
+
+    "finish the congestion management correctly" in {
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala:60]: What about other behaviours / cases to test? Or is there just finishing the CM?

**Review by danielfeismann — CHANGES_REQUESTED** [review]
Looks good, just the question on completeness of the test cases.

File: src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala (hunk 2 above)
Comment (staudtMarius) [reply src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala:60]: There is also a behavior, that starts the congestion management. I will add a test for that behavior as well.

**Comment by staudtMarius** [comment]
@danielfeismann Short notice, I moved the test `CongestedComponentsSpec` to be in line with the class structure.

**Review by danielfeismann — APPROVED** [review]
LGTM
